name: 'osv-scanner'
on: [push, pull_request]

description: 'Scans your directory against the OSV database'
inputs:
  to-scan:
    description: 'Directory to scan'
    required: true
    default: '/github/workspace'
  version:
    description: 'osv-scanner version to use'
    required: true
    default: '1.1.0'
  arch:
    description: 'osv-scanner architecture'
    required: false
    default: 'amd64'
runs:
  using: 'docker'
  image: 'ghcr.io/google/osv-scanner:${{ inputs.version }}-${{ inputs.arch }}'
  args:
    - '--skip-git'
    - ${{ inputs.to-scan }}